
sudo: false
language: java
jdk: openjdk8

cache:
    directories:
    - "$HOME/.m2"

# Possibly download settings from a 'parent' project
# https://raw.githubusercontent.com/nano-io/nano-time/master/settings.xml
install:
  - /bin/cp settings.xml $HOME/.m2/settings.xml
  - mvn -B --show-version dependency:resolve

script: mvn -B verify

deploy:
  - provider: script
    script: mvn -B -DskipTests deploy
    skip_cleanup: true
    on:
        tags: true
